apiVersion: v1
kind: ConfigMap
metadata:
  name: user-ms-config
data:
  appsettings.json: |-
  {
    "Logging": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    },
    "AllowedHosts": "*",
    "ConnectionStrings": {
      "DefaultConnection": "server=34.101.244.20; port=3306; database=test; user=root; password=Izeno123!; Persist Security Info=False; Connect Timeout=300"
    }
  }
