apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi-app
  labels:
    app: userapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi-app
  template:
    metadata:
      labels:
        app: userapi-app
    spec:
      containers:
      - name: configmapfileprovidersample
        imagePullPolicy: Always
        image: default-route-openshift-image-registry.apps.ocpprd.izeno.biz/yohanes-study/usermsapi:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: user-ms-config